//* Custom Styles
import '../../components/LoadSpinner/LoadSpinner.css'

export const LoadSpinner = () => {
  return (
    <section className='Spinner-wrapper'>
      {/* generated by https://loading.io/  */}
      <div className='spinner'>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </section>
  )
}
