//* Custom Styles
import '../../components/LoadSpinner/LoadSpinner.css'

export const LoadSpinner = () => {
  return (
    <>
      <section className='FeatureContainer LoadSpinner'>
        {/* generated by https://loading.io/  */}
        <div
          className='LoadSpinner-Wrapper
        '>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </section>
    </>
  )
}
