//* Custom Styles
import '../../components/LoadSpinner/LoadSpinner.css'

export const LoadSpinner = () => {
  return (
    <main className='LoadSpinner-Container' role='alert' aria-live='assertive'>
      {/* generated by https://loading.io/  */}
      <section className='LoadSpinner'>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </section>
    </main>
  )
}
